version: "3.7"
services:
  uwsgi:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    expose:
      - 5000
    environment:
      SECRET_KEY: ${SECRET_KEY}
      VIRTUAL_HOST: f1recloud.com
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      DEBUG: ${DEBUG}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    restart: always
    volumes:
      - ./:/app/
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: scripts/nginx/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - uwsgi
    volumes:
      - ./static/:/static/
      - ./media/:/media/

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    expose:
    - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres_data:
